services:
  mysqldb:
    image: mysql:8.3
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
      MYSQL_USER: ${MYSQLDB_USER}
      MYSQL_PASSWORD: ${MYSQLDB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - mysqlvolume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /usr/src/estoqueige
    restart: on-failure
    env_file: ./.env
    ports:
      - "${SPRING_DOCKER_PORT}:${SPRING_LOCAL_PORT}"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb/${MYSQLDB_DATABASE}?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: ${MYSQLDB_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQLDB_PASSWORD}
      USER_LOGIN: ${USER_LOGIN}
      USER_PASSWORD: ${USER_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      FRONTEND_HOST: ${FRONTEND_HOST}
      FRONTEND_HOST_PORT: ${FRONTEND_HOST_PORT}
    volumes:
      - .m2:/root/.m2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    stdin_open: true
    tty: true

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_HOST: ${NEXT_PUBLIC_BACKEND_HOST}
    working_dir: /usr/src/app
    env_file: ./.env
    ports:
      - "3001:3000"
    environment:
      NEXT_PUBLIC_BACKEND_HOST: ${NEXT_PUBLIC_BACKEND_HOST}
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  mysqlvolume: